// Code generated by "enumer -type AttrType -linecomment -text"; DO NOT EDIT.

package metal

import (
	"fmt"
	"strings"
)

const _AttrTypeName = "GMZARCEHSB"

var _AttrTypeIndex = [...]uint8{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

const _AttrTypeLowerName = "gmzarcehsb"

func (i AttrType) String() string {
	if i < 0 || i >= AttrType(len(_AttrTypeIndex)-1) {
		return fmt.Sprintf("AttrType(%d)", i)
	}
	return _AttrTypeName[_AttrTypeIndex[i]:_AttrTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _AttrTypeNoOp() {
	var x [1]struct{}
	_ = x[GlobalAttr-(0)]
	_ = x[ModelAttr-(1)]
	_ = x[ZoneAttr-(2)]
	_ = x[ApplianceAttr-(3)]
	_ = x[RackAttr-(4)]
	_ = x[ClusterAttr-(5)]
	_ = x[EnvironmentAttr-(6)]
	_ = x[HostAttr-(7)]
	_ = x[SwitchAttr-(8)]
	_ = x[BMCAttr-(9)]
}

var _AttrTypeValues = []AttrType{GlobalAttr, ModelAttr, ZoneAttr, ApplianceAttr, RackAttr, ClusterAttr, EnvironmentAttr, HostAttr, SwitchAttr, BMCAttr}

var _AttrTypeNameToValueMap = map[string]AttrType{
	_AttrTypeName[0:1]:       GlobalAttr,
	_AttrTypeLowerName[0:1]:  GlobalAttr,
	_AttrTypeName[1:2]:       ModelAttr,
	_AttrTypeLowerName[1:2]:  ModelAttr,
	_AttrTypeName[2:3]:       ZoneAttr,
	_AttrTypeLowerName[2:3]:  ZoneAttr,
	_AttrTypeName[3:4]:       ApplianceAttr,
	_AttrTypeLowerName[3:4]:  ApplianceAttr,
	_AttrTypeName[4:5]:       RackAttr,
	_AttrTypeLowerName[4:5]:  RackAttr,
	_AttrTypeName[5:6]:       ClusterAttr,
	_AttrTypeLowerName[5:6]:  ClusterAttr,
	_AttrTypeName[6:7]:       EnvironmentAttr,
	_AttrTypeLowerName[6:7]:  EnvironmentAttr,
	_AttrTypeName[7:8]:       HostAttr,
	_AttrTypeLowerName[7:8]:  HostAttr,
	_AttrTypeName[8:9]:       SwitchAttr,
	_AttrTypeLowerName[8:9]:  SwitchAttr,
	_AttrTypeName[9:10]:      BMCAttr,
	_AttrTypeLowerName[9:10]: BMCAttr,
}

var _AttrTypeNames = []string{
	_AttrTypeName[0:1],
	_AttrTypeName[1:2],
	_AttrTypeName[2:3],
	_AttrTypeName[3:4],
	_AttrTypeName[4:5],
	_AttrTypeName[5:6],
	_AttrTypeName[6:7],
	_AttrTypeName[7:8],
	_AttrTypeName[8:9],
	_AttrTypeName[9:10],
}

// AttrTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func AttrTypeString(s string) (AttrType, error) {
	if val, ok := _AttrTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _AttrTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to AttrType values", s)
}

// AttrTypeValues returns all values of the enum
func AttrTypeValues() []AttrType {
	return _AttrTypeValues
}

// AttrTypeStrings returns a slice of all String values of the enum
func AttrTypeStrings() []string {
	strs := make([]string, len(_AttrTypeNames))
	copy(strs, _AttrTypeNames)
	return strs
}

// IsAAttrType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i AttrType) IsAAttrType() bool {
	for _, v := range _AttrTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for AttrType
func (i AttrType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for AttrType
func (i *AttrType) UnmarshalText(text []byte) error {
	var err error
	*i, err = AttrTypeString(string(text))
	return err
}
