// Code generated by "enumer -type level -linecomment -text"; DO NOT EDIT.

package logging

import (
	"fmt"
	"strings"
)

const (
	_levelName_0      = "debug"
	_levelLowerName_0 = "debug"
	_levelName_1      = "info"
	_levelLowerName_1 = "info"
	_levelName_2      = "warn"
	_levelLowerName_2 = "warn"
	_levelName_3      = "error"
	_levelLowerName_3 = "error"
)

var (
	_levelIndex_0 = [...]uint8{0, 5}
	_levelIndex_1 = [...]uint8{0, 4}
	_levelIndex_2 = [...]uint8{0, 4}
	_levelIndex_3 = [...]uint8{0, 5}
)

func (i level) String() string {
	switch {
	case i == -4:
		return _levelName_0
	case i == 0:
		return _levelName_1
	case i == 4:
		return _levelName_2
	case i == 8:
		return _levelName_3
	default:
		return fmt.Sprintf("level(%d)", i)
	}
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _levelNoOp() {
	var x [1]struct{}
	_ = x[levelDebug-(-4)]
	_ = x[levelInfo-(0)]
	_ = x[levelWarn-(4)]
	_ = x[levelError-(8)]
}

var _levelValues = []level{levelDebug, levelInfo, levelWarn, levelError}

var _levelNameToValueMap = map[string]level{
	_levelName_0[0:5]:      levelDebug,
	_levelLowerName_0[0:5]: levelDebug,
	_levelName_1[0:4]:      levelInfo,
	_levelLowerName_1[0:4]: levelInfo,
	_levelName_2[0:4]:      levelWarn,
	_levelLowerName_2[0:4]: levelWarn,
	_levelName_3[0:5]:      levelError,
	_levelLowerName_3[0:5]: levelError,
}

var _levelNames = []string{
	_levelName_0[0:5],
	_levelName_1[0:4],
	_levelName_2[0:4],
	_levelName_3[0:5],
}

// levelString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func levelString(s string) (level, error) {
	if val, ok := _levelNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _levelNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to level values", s)
}

// levelValues returns all values of the enum
func levelValues() []level {
	return _levelValues
}

// levelStrings returns a slice of all String values of the enum
func levelStrings() []string {
	strs := make([]string, len(_levelNames))
	copy(strs, _levelNames)
	return strs
}

// IsAlevel returns "true" if the value is listed in the enum definition. "false" otherwise
func (i level) IsAlevel() bool {
	for _, v := range _levelValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for level
func (i level) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for level
func (i *level) UnmarshalText(text []byte) error {
	var err error
	*i, err = levelString(string(text))
	return err
}
