edition = "2023";

package proto.metal.v1;

import "google/protobuf/go_features.proto";
import "proto/metal/v1/enums.proto";

option go_package = "github.com/endobit/gen/go/proto/metal/v1;metalv1";

message CreateSchemaRequest {
  option features.(pb.go).api_level = API_OPAQUE;
  Schema schema = 1;
}

message ReadSchemaRequest {
  option features.(pb.go).api_level = API_OPAQUE;
  string zone = 1;
  string cluster = 2;
  string host = 3;
}

message ReadSchemaResponse {
  option features.(pb.go).api_level = API_OPAQUE;
  Schema schema = 1;
}

message Schema {
  map<string, string> attributes = 1;
  repeated Make makes = 2;
  repeated Zone zones = 3;
  repeated Software software = 4;
  repeated Stack stacks = 5;
}

message ZoneScope {
  string zone = 1;
}

message ClusterScope {
  string zone = 1;
  string cluster = 2;
}

message HostScope {
  string zone = 1;
  string cluster = 2;
  string host = 3;
}

message Software {
  string name = 1;
  string type = 2;
  string url = 3;
  string key_url = 4;
  string architecture = 5;
}

message Stack {
  string name = 1;
  string os_name = 2;
  string os_flavor = 3;
  string os_version = 4;
  repeated string software = 5;
}

message Make {
  string name = 1;
  repeated Model models = 2;
}

message Model {
  map<string, string> attributes = 1;
  string name = 2;
  string architecture = 3;
}

message Zone {
  map<string, string> attributes = 1;
  string name = 2;
  string time_zone = 3;
  repeated Network networks = 4;
  repeated Appliance appliances = 5;
  repeated Environment environments = 6;
  repeated Rack racks = 7;
  repeated Host hosts = 8;		// non-clustered hosts
  repeated Cluster clusters = 9;
}

message Network {
  ZoneScope scope = 1;
  string name = 2;
  string address = 3;
  string gateway = 4;
  bool pxe = 5;
  uint32 mtu = 6;
}

message Cluster {
  ZoneScope scope = 1;
  map<string, string> attributes = 2;
  string name = 3;
  repeated Host hosts = 4;
  repeated Switch switches = 5;
}

message Appliance {
  ClusterScope scope = 1;
  map<string, string> attributes = 2;
  string name = 3;
}

message Environment {
  ClusterScope scope = 1;
  map<string, string> attributes = 2;
  string name = 3;
}

message Rack {
  ClusterScope scope = 1;
  map<string, string> attributes = 2;
  string name = 3;
}

message Host {
  message Interface {
    HostScope scope = 1;
    string name = 2;
    string ip = 3;
    string mac = 4;
    bool dhcp = 5;
    bool pxe = 6;
    bool management = 7;
    string type = 8;
    string bond_mode = 9;
    repeated string sub_devices = 10;
    string network = 11;
    string gateway = 12;
    uint32 mtu = 13;
  }

  ClusterScope scope = 1;
  map<string, string> attributes = 2;
  string name = 3;
  string make = 4;
  string model = 5;
  string environment = 6;
  string location = 7;
  string rack = 8;
  uint32 rank = 9;
  uint32 slot = 10;
  string type = 11;
  string appliance = 12;
  BMC bmc = 13;
  repeated Interface interfaces = 14;
}

message BMC {
  message Interface {
    string name = 1;
    string network = 2;
    string ip = 3;
    string mac = 4;
    bool dhcp = 5;
  }

  ClusterScope scope = 1;
  map<string, string> attributes = 2;
  string name = 3;
  string model = 4;
  string environment = 5;
  repeated Interface interfaces = 6;
}

message Switch {
  message Interface {
    string name = 1;
  }

  ZoneScope scope = 1;
  map<string, string> attributes = 2;
  string name = 3;
  string model = 4;
  string environment = 5;
  string rack = 6;
  string rank = 7;
  repeated Interface interfaces = 8;
}

